# Generated by Django 3.0.8 on 2020-07-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_message_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
