# Generated by Django 3.0.8 on 2020-08-06 18:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20200802_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='likers',
            field=models.ManyToManyField(related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
